### ISSUE TITLE
Thank you, make deploy issue

### ISSUE THREAD

**Issue by fusion27** [mjehrhart/sam-rust-template#1]
# THANK YOU !!

First, massive stacks of thanks for posting this.  I'm a complete noob with Rust, your project represents my first exposure.  Thank you thank you!

## Off to a great start

Running Ubuntu Linux Ubuntu 20.04.4.  Your setup guide worked as expected for me. Was able to successfully compile and build Docker image. 

## Seeing the following with `make deploy`
```
2022-05-22 11:41:53 ~/Projects/Personal/sam-rust-template@SW-141_Casey_Wise✗✗ % make deploy
if [ -f samconfig.toml ]; \
        then sam deploy --stack-name stack-sam-rust-template; \
        else sam deploy -g --stack-name stack-sam-rust-template; \
fi

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [stack-sam-rust-template]: 
        AWS Region [us-east-2]: 
Traceback (most recent call last):
  File "samcli/lib/samlib/wrapper.py", line 78, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 147, in parse
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('PutFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "samcli/lib/cli_validation/image_repository_validation.py", line 76, in wrapped
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 152, in wrapped
  File "samcli/lib/telemetry/metric.py", line 121, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/deploy/command.py", line 230, in cli
  File "samcli/commands/deploy/command.py", line 289, in do_cli
  File "samcli/commands/deploy/guided_context.py", line 347, in run
  File "samcli/commands/deploy/guided_context.py", line 134, in guided_prompts
  File "samcli/lib/providers/sam_stack_provider.py", line 231, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 53, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 171, in get_template
  File "samcli/lib/samlib/wrapper.py", line 82, in run_plugins
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('PutFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')] ('PutFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')
[582201] Failed to execute script __main__
make: *** [Makefile:50: deploy] Error 255
```

**Comment by fusion27** [comment]
My SAM CLI version
```
sam --version
SAM CLI, version 1.21.1
```

**Comment by mjehrhart** [comment]
So, you run Make Deploy and then you answer a few questions on the terminal screen.  and at that point, you receive the error list, is that correct? Are you able to answer all the questions or does it stop after asking you about which default region you want?

hmmmm.
on macOS I run: SAM CLI, version 1.48.0
